import { Injectable, Logger } from '@nestjs/common';
import { SupabaseService } from 'supabase-lib';
import * as CryptoJS from 'crypto-js';
import {
  SignContractDto,
  GenerateContractDto,
  RegenerateContractDto,
  ChangeRequestDto,
} from './dto/contract.dto';

@Injectable()
export class ContractService {
  private readonly logger = new Logger(ContractService.name);

  constructor(private supabase: SupabaseService) {}

  async generateFromPrompt(data: GenerateContractDto) {
    const client = this.supabase.getClient();

    const { data: contract, error: contractError } = await client
      .from('contracts')
      .insert([
        {
          tenant_id: data.tenantId,
          creator_id: data.userId,
          client_id: data.clientId,
          template_id: data.templateId,
          title: 'AI Generated Contract',
          status: 'draft',
          ai_enhanced: true,
          original_description: data.prompt,
        },
      ])
      .select()
      .single();

    if (contractError) throw contractError;

    // TODO: replace with real Gemini/OpenAI call once GOOGLE_GENERATIVE_AI_API_KEY is set
    const content = `# Service Agreement for ${data.prompt}\n\nGenerated by Velluma AI...`;

    const { error: versionError } = await client
      .from('contract_documents')
      .insert([
        {
          contract_id: contract.id,
          tenant_id: data.tenantId,
          author_id: data.userId,
          content: { text: content },
          source: 'ai',
          ai_prompt: data.prompt,
          regen_number: 0,
        },
      ]);

    if (versionError) throw versionError;

    return { contractId: contract.id, content };
  }

  async signContract(data: SignContractDto) {
    const client = this.supabase.getClient();

    // 1. Fetch current contract state
    const { data: contract, error: fetchError } = await client
      .from('contracts')
      .select('*')
      .eq('id', data.contractId)
      .single();

    if (fetchError || !contract) throw new Error('Contract not found');

    // 2. Prevent duplicate signatures from the same user on the same contract
    const { data: existing } = await client
      .from('contract_signatures')
      .select('id')
      .eq('contract_id', data.contractId)
      .eq('user_id', data.userId)
      .maybeSingle();

    if (existing) {
      throw new Error(
        `User ${data.userId} has already signed contract ${data.contractId}`,
      );
    }

    // 3. Generate cryptographic hash of the latest document version
    const { data: latestDoc } = await client
      .from('contract_documents')
      .select('*')
      .eq('contract_id', data.contractId)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    const agreementPayload = JSON.stringify({
      contractId: contract.id,
      content: latestDoc?.content,
      timestamp: new Date().toISOString(),
    });

    const agreementHash = CryptoJS.SHA256(agreementPayload).toString();

    // 4. Record signature
    const { error: sigError } = await client
      .from('contract_signatures')
      .insert([
        {
          contract_id: data.contractId,
          tenant_id: data.tenantId,
          user_id: data.userId,
          signer_role: data.role,
          signature_data: data.signatureBase64,
          signature_type: 'canvas',
          version_id: latestDoc?.id,
        },
      ]);

    if (sigError) throw sigError;

    // 5. Record audit log
    await client.from('audit_logs').insert([
      {
        tenant_id: data.tenantId,
        user_id: data.userId,
        action: 'contract_signed',
        resource_type: 'contract',
        resource_id: data.contractId,
        metadata: {
          agreement_hash: agreementHash,
          role: data.role,
        },
      },
    ]);

    // 6. Check if all parties signed and finalize
    const { data: isFinalized } = await client.rpc(
      'finalize_contract_if_all_signed',
      {
        p_contract_id: data.contractId,
      },
    );

    return {
      success: true,
      agreementHash,
      isFinalized,
      signedAt: new Date().toISOString(),
    };
  }

  async createChangeRequest(data: ChangeRequestDto) {
    const client = this.supabase.getClient();

    const { data: request, error } = await client
      .from('contract_change_requests')
      .insert([
        {
          contract_id: data.contractId,
          tenant_id: data.tenantId,
          requester_id: data.requesterId,
          details: data.details,
          proposed_changes: data.proposedChanges,
          status: 'open',
        },
      ])
      .select()
      .single();

    if (error) throw error;
    return request;
  }

  async getAuditLog(contractId: string) {
    const { data, error } = await this.supabase
      .getClient()
      .from('audit_logs')
      .select('*')
      .eq('resource_id', contractId)
      .eq('resource_type', 'contract')
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data;
  }
}
